# Generated by Django 5.2.6 on 2025-11-11 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('mom', 'Mom'), ('dad', 'Dad'), ('mother_in_law', 'Mother-in-law'), ('father_in_law', 'Father-in-law'), ('son', 'Son'), ('daughter', 'Daughter'), ('friend', 'Friend'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('other', 'Other')], max_length=20)),
                ('sub_relation', models.CharField(choices=[('bridal_side', 'Bridal Side'), ('groom_side', 'Groom Side'), ('both', 'Both'), ('none', 'None')], default='none', max_length=20)),
                ('message', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Guest Message',
                'verbose_name_plural': 'Guest Messages',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
